/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        navy: {
          DEFAULT: '#071a3d',
          50: '#e8edf5',
          100: '#c5d0e6',
          200: '#8fa5cc',
          300: '#5a7ab3',
          400: '#2d5499',
          500: '#071a3d',
          600: '#061633',
          700: '#041129',
          800: '#030c1f',
          900: '#020814',
        },
        gold: {
          DEFAULT: '#c59a42',
          50: '#fdf8ee',
          100: '#f9edcc',
          200: '#f2d999',
          300: '#e8c066',
          400: '#dba83d',
          500: '#c59a42',
          600: '#a67e32',
          700: '#876325',
          800: '#684c1b',
          900: '#4a3512',
        },
        cream: '#f8f3e8',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-gold': 'pulseGold 2s infinite',
        'float': 'float 3s ease-in-out infinite',
        'float-slow': 'float 5s ease-in-out infinite',
        'float-delayed': 'float 4s ease-in-out 1s infinite',
        'blink-flower': 'blinkFlower 1.5s ease-in-out infinite',
        'blink-flower-2': 'blinkFlower 2s ease-in-out 0.5s infinite',
        'blink-flower-3': 'blinkFlower 1.8s ease-in-out 1s infinite',
        'spin-slow': 'spin 8s linear infinite',
        'shimmer': 'shimmer 2.5s ease-in-out infinite',
        'confetti-1': 'confetti1 4s ease-in-out infinite',
        'confetti-2': 'confetti2 3.5s ease-in-out 0.7s infinite',
        'confetti-3': 'confetti3 5s ease-in-out 1.2s infinite',
        'confetti-4': 'confetti4 4.5s ease-in-out 0.3s infinite',
        'star-pulse': 'starPulse 1.5s ease-in-out infinite',
        'ribbon': 'ribbon 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { transform: 'translateY(10px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        pulseGold: { '0%,100%': { boxShadow: '0 0 0 0 rgba(197,154,66,0.4)' }, '50%': { boxShadow: '0 0 0 8px rgba(197,154,66,0)' } },
        float: { '0%,100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-12px)' } },
        blinkFlower: { '0%,100%': { opacity: '1', transform: 'scale(1)' }, '50%': { opacity: '0.3', transform: 'scale(0.85)' } },
        shimmer: { '0%,100%': { opacity: '0.7' }, '50%': { opacity: '1' } },
        starPulse: { '0%,100%': { transform: 'scale(1)', opacity: '1' }, '50%': { transform: 'scale(1.3)', opacity: '0.6' } },
        ribbon: { '0%,100%': { transform: 'rotate(-2deg)' }, '50%': { transform: 'rotate(2deg)' } },
        confetti1: { '0%': { transform: 'translateY(-10px) rotate(0deg)', opacity: '1' }, '100%': { transform: 'translateY(80px) rotate(360deg)', opacity: '0' } },
        confetti2: { '0%': { transform: 'translateY(-10px) rotate(0deg)', opacity: '1' }, '100%': { transform: 'translateY(70px) rotate(-270deg)', opacity: '0' } },
        confetti3: { '0%': { transform: 'translateY(-10px) rotate(0deg)', opacity: '1' }, '100%': { transform: 'translateY(90px) rotate(180deg)', opacity: '0' } },
        confetti4: { '0%': { transform: 'translateY(-10px) rotate(0deg)', opacity: '1' }, '100%': { transform: 'translateY(75px) rotate(-360deg)', opacity: '0' } },
      },
    },
  },
  plugins: [],
}
